version: '3.3'
services:
  drupal:
    stdin_open: true
    tty: true
    image: "ricardoamaro/drupal8"
    ports:
      - 8400:80
    volumes:
      - ./local/data:/var/lib/mysql
      - ./local:/var/www/html
    restart: always
